public enum CharacterState
{
    NORMAL, START_ROLLING, ROLLING, DEAD, DISABLED
}
public enum EnemyState
{
    IDLE, WALKING, RUNNING, ATTACK, SURPRISE, DEAD, DISABLED
}
public enum RollingDirection
{
    ROLLING_FORWARD, ROLLING_BACKWARD, ROLLING_RIGHT, ROLLING_LEFT
}
public enum ItemType
{
    AMMO_PISTOL, AMMO_SHOTGUN, AMMO_ASSAULT_AK, AMMO_ASSAULT_M4, AMMO_SNIPER, GREEN_HERB, RED_HERB 
}
